icons:
  # list of icons to appear
- name: Gitlab
  link: www.gitlab.com
  image: https://about.gitlab.com/images/press/logo/png/gitlab-logo-gray-stacked-rgb.png
auth:
  # oauth basic details
  client_id: <oauth clientid>
  client_secret: <oauth client secret>
  callback_url: <oauth callback>
  provider_url: <oauth provider url>
  state: state